DELETE http://localhost:3003/api/blogs/63445ad381deb466cc53594b
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRpZWdvcnJhbW9zIiwiaWQiOiI2MzQ0NWFkMzgxZGViNDY2Y2M1MzU5NGIiLCJpYXQiOjE2Njc0OTIyMzZ9.RdJM6sSpM7OoW5e7uu5U94ddOa84bw647pn7_a0c3nY
